export const CloseGroup = 'close-group'
export const ConfigureLargeFileLimit = 'configure-large-file-limit'
export const OpenLargeFile = 'open-large-file'
export const OpenInTextEditor = 'open-in-text-editor'
export const RetryOpen = 'retry-open'
export const RestoreClosedTab = 'restore-closed-tab'
export const SplitRight = 'split-right'
export const TogglePreview = 'toggle-preview'
